## Neden TensorFlow?
Sıfırdan makine öğrenimi ve derin öğrenme modelleri oluşturmak yerine TensorFlow gibi bir kitaplık kullanmanız yapmak istediğiniz projeyi daha hızlı ve daha efektif bitirmenizi sağlayacaktır. Diğer bir nedeni ise; TensorFlow her zaman güncel bir kütüphanedir, kullanmak istediğiniz tüm makine öğrenimi işlevlerinin çoğunu içeriyor.

## Tensör Nedir?
Tensörler, makine öğrenimi sistemleri tarafından kullanılan veri yapısıdır ve onları tanımak, önceden geliştirmeniz gereken önemli bir beceridir.

Bir tensör, sayısal veriler için bir kaptır. Sistemimizde kullanacağımız bilgileri saklama yöntemimiz budur.

Üç özellik bir tensörü tanımlar:
- Sıra
- Şekil
- Veri Tipi
Burada bir tensörün rankı, tensörün eksen sayısını ifade eder.

Örnekler:
- Bir matrisin rankı 2'dir çünkü iki ekseni vardır.
- Bir vektörün rankı 1'dir çünkü tek eksene sahiptir.

Bir tensörün şekli, her eksen boyunca boyutların sayısını ifade eder.

Örnekler:
- Bir kare matrisin (2, 2) boyutları olabilir.
- Seviye 3 tensörünün (3, 5, 8) boyutları olabilir.

Tensörün veri türü, içerdiği veri türünü ifade eder.
Desteklenen veri türlerinden bazıları şunlardır:
- float32
- float64
- uint8
- int32
- int64



In [2]:
# TensorFlow'u içeri alma
import tensorflow as tf
print(tf.__version__) # bu versiyonun 2.+ fazla olması kritiktir

2.5.0


## `tf.constant()` ile Tensor Oluşturma
Tensör TensorFlow kullanmadan yaratmamız pek mümkün değil. Bunun nedeni; TensorFlow'un veri kaynaklarınızı okuyabilen ve bunları otomatik olarak tensörlere dönüştürebilen yerleşik modüllere (tf.io ve tf.data gibi) sahip olması ve daha sonra sinir ağı modellerinin bunları bizim için işlemesidir.

Ama şimdilik, tensörflerin kendilerine ve onları nasıl manipüle edeceğimize aşına olduğumuz için, onları kendimiz nasıl yarabileceğimizi göreceğiz.

In [3]:
# bir scalar yartma (rank'ı 0 olan)
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

Bir skaler, sıra 0 tensörü olarak bilinir. Çünkü boyutları yoktur (sadece bir sayıdır).

> 🔑 **Not:** <br> Şimdilik, farklı tensör dereceleri hakkında çok fazla bilgi sahibi olmanıza gerek yok (ancak bunu daha sonra göreceğiz). Önemli olan nokta, tensörlerin sınırsız bir boyut aralığına sahip olabileceğini bilmektir (tam miktar, temsil ettiğiniz verilere bağlı olacaktır).

In [4]:
# Bir tensörün boyut sayısını kontrol edin (ndim, boyut sayısı anlamına gelir)
scalar.ndim

0

In [5]:
# bir vector yaratma (boyutu 0'dan büyük olan)
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check the number of dimensions of our vector tensor
vector.ndim

1

In [7]:
# bir matrix yartma (boyutu 1'den büyük olan)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

Varsayılan olarak, TensorFlow, int32 veya float32 veri türüyle tensörler oluşturur.

Bu, 32 bit hassasiyet olarak bilinir (sayı ne kadar yüksekse, sayı o kadar kesin, bilgisayarınızda o kadar fazla yer kaplar).

In [9]:
# Başka bir matris oluşturun ve veri türünü tanımlayın
another_matrix = tf.constant([[10., 7.], 
                              [3., 2.], 
                              [8., 9.]], dtype=tf.float16) # spesifik bir datatype tanımladım
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
# Another_matrix daha fazla sayı içerse de boyutları aynı kalır
another_matrix.ndim

2

In [11]:
# Bir tensöre ne dersiniz? 
# (2'den fazla boyut, ancak yukarıdaki öğelerin tümü aynı zamanda teknik olarak tensördür)

tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

Bu, derece 3 tensör (3 boyutlu) olarak bilinir, ancak bir tensör keyfi (sınırsız) miktarda boyuta sahip olabilir.

Örneğin, bir dizi görüntüyü şekilli (224, 224, 3, 32) tensörlere dönüştürebilirsiniz, burada:
- 224, 224 (ilk 2 boyut), görüntülerin piksel cinsinden yükseklik ve genişliğidir.
- 3, görüntünün renk kanallarının sayısıdır (kırmızı, yeşil mavi).
- 32, batch-size (sinir ağının herhangi bir zamanda gördüğü görüntü sayısı).

Yarattığımız yukarıdaki değişkenlerin tümü aslında tensörlerdir. Ama aynı zamanda farklı isimlerle anıldığını da duyabilirsiniz (onlara verdiğimiz isimler):
- **scalar:** tek bir sayı.
- **vektor:** yönü olan bir sayı (örneğin, yönü olan rüzgar hızı).
- **matrix:** 2 boyutlu bir sayı dizisi.
- **tensor:** n-boyutlu bir sayı dizisi (n herhangi bir sayı olabilir, 0-boyutlu bir tensör bir skalerdir, 1-boyutlu bir tensör bir vektördür).

Karışıklığa ek olarak, matris ve tensör terimleri sıklıkla birbirinin yerine kullanılır.

TensorFlow kullandığımızdan beri, atıfta bulunduğumuz ve kullandığımız her şey tensör olacaktır.

<img src="https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-scalar-vector-matrix-tensor.png" />

## `tf.Variable()` ile Tensor Oluşturma

tf.Variable() ve tf.constant() arasındaki fark, tf.constant() ile oluşturulan tensörlerin değişmez olmasıdır (değiştirilemez, yalnızca yeni bir tensör oluşturmak için kullanılabilir), burada tf.Variable() ile oluşturulan tensörler  değişkendir (değiştirilebilir).



In [13]:
# tf.Variable ve tf.constant ile tensor oluşturma
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# constant değerini değiştirmeye çalıştığımız için hata alacağız
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [15]:
# şimdi aynısını tf.variable için deneyelim (bir hata almayacağız)
changeable_tensor[0].assign(5)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 7], dtype=int32)>

**Hangisini kullanmalısınız? tf.constant() veya tf.Variable()?**

Sorununuzun ne gerektirdiğine bağlı olacaktır. Ancak çoğu zaman TensorFlow sizin için otomatik olarak seçim yapar (veri yüklerken veya verileri modellerken).

## Random Tensor Oluşturma

Rastgele tensörler, rastgele sayılar içeren bazı sonsuz boyuttaki tensörlerdir.

**Neden rastgele tensörler oluşturmak isteyesiniz?**
- Bu, sinir ağlarının verilerde öğrenmeye çalıştıkları ağırlıklarını (kalıplarını) başlatmak için kullandıkları şeydir.
- **Örneğin**, bir sinir ağı öğrenme süreci genellikle rastgele bir n-boyutlu sayı dizisini almayı ve bir tür deseni temsil edene kadar (orijinal verileri temsil etmenin sıkıştırılmış bir yolu) iyileştirmeyi içerir.

**Bir network nasıl öğrenir?**
<img src="https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-how-a-network-learns.png" />
Bir ağ, rastgele kalıplarla (1) başlayarak, ardından örnekleri (3) temsil etmek için rastgele kalıplarını güncellemeye çalışırken, açıklayıcı veri örneklerinden (2) geçerek öğrenir.

[`tf.random.Generator`](https://www.tensorflow.org/guide/random_numbers#the_tfrandomgenerator_class) sınıfını kullanarak rastgele tensörler oluşturabiliriz.

In [16]:
# iki random tensor oluşturma 
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2)) # normal dağılımlı bir tensor oluşturma
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# sence bunlar aynı mı çıkacak?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Yaptığımız rastgele tensorler aslında sahte rasgele sayılardır (rastgele görünürler, ancak gerçekte değildirler).

Bir seed ayarlarsak, aynı rastgele sayıları elde ederiz (eğer NumPy'yi daha önce kullandıysanız, bu np.random.seed(42)'ye benzer).

seed ayarlamak, "hey, bazı rasgele sayılar oluşturun, ancak bunları X ile tatlandırın" der (X seed'tir).

seed değiştirdiğimizde sizce ne olacak?

In [17]:
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3, 2))

random_3, random_4, random_1 == random_3, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

Bir tensörün sırasını karıştırmak isterseniz ne olur?

Bekle, neden bunu yapmak isteyesin ki?

Diyelim ki 15.000 kedi ve köpek resmiyle çalışıyorsunuz ve ilk 10.000 resim kedi ve sonraki 5.000 resim köpekti. Bu sıra, bir sinir ağının nasıl öğrendiğini etkileyebilir (verilerin sırasını öğrenerek fazla gelebilir), bunun yerine verilerinizi hareket ettirmek iyi bir fikir olabilir.

In [18]:
# Bir tensor karıştır(shuffle) (verilerinizi karıştırmak istediğinizde değerlidir)
not_shuffled = tf.constant([[10, 7],
                            [3, 4], 
                            [2, 5]])
# her seferinde farklı sonuçlar alır
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [19]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

## Tensor Oluşturmanın Diğer Yolları

Bunları nadiren kullanabilseniz de (unutmayın, perde arkasında sizin için birçok tensör işlemi yapılır), tüm birlerden bir tensör oluşturmak için tf.ones() ve tüm sıfırlardan bir tensör oluşturmak için tf.zeros() kullanabilirsiniz.

In [20]:
# birlerden oluşan bir tensor yaratmak için
tf.ones(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [21]:
# sıfırlardan oluşan bir tensor yaratmak için
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

NumPy dizilerini tensörlere de dönüştürebilirsiniz.

Unutmayın, tensörler ve NumPy dizileri arasındaki temel fark, tensörlerin GPU'larda çalıştırılabilmesidir.

> **Not:** <br>
Bir matris veya tensör tipik olarak büyük harfle (ör. X veya A) temsil edilirken vektör olarak tipik olarak küçük harfle (ör. y veya b) temsil edilir.

In [22]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
A = tf.constant(numpy_A, shape=[2, 4, 3])

numpy_A, A, A.ndim

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>,
 3)

## Tensor'lerden Bilgi Alma (shape, rank, size)

Tensörlerinizden farklı bilgi parçaları almak isteyeceğiniz zamanlar olacaktır, özellikle aşağıdaki tensör kelimesini bilmelisiniz:

- **Shape:** <br> Bir tensörün her bir boyutunun uzunluğu (eleman sayısı).
- **Rank:** <br> Tensör boyutlarının sayısı. Bir skaler rank 0'a, bir vektör rank 1'e, bir matris rank 2'ye, bir tensör rank n'ye sahiptir.
- **Axis veya Dimension:** <br> Bir tensörün belirli bir boyutu.
- **Size:** <br> Tensördeki toplam öğe sayısı.
Bunları özellikle verilerinizin şekillerini modelinizin şekilleriyle hizalamaya çalışırken kullanacaksınız. Örneğin, görüntü tensörlerinizin şeklinin, modelinizin giriş katmanıyla aynı şekle sahip olduğundan emin olun.

Bunlardan birini **ndim** niteliğini kullanmadan önce görmüştük. Gerisini görelim.

In [23]:
# rank'ı 4 olan bir tensor yaratma
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [24]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [25]:
# Tensörün çeşitli özellikleri
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


Ayrıca Python listeleri gibi tensörleri de indeksleyebilirsiniz.

In [26]:
# Her boyutun ilk 2 öğesini al
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [27]:
# Sonuncusu hariç her dizinden boyutu al
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
# rank'ı 2 olan bir tensor
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# her satırda ki son değeri al
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

Aynı bilgiyi `tf.newaxis` kullanarak mevcut tutarken tensörünüze boyutlar da ekleyebilirsiniz.

In [29]:
# boyut ekleme
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_2_tensor, rank_3_tensor # shape (2, 2), shape (2, 2, 1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

Aynısını `tf.expand_dims()` kullanarak da elde edebilirsiniz.

In [30]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

## Tensorleri Manipüle Etme (Tensor işlemleri)
Tensörlerdeki kalıpları bulmak (verilerin sayısal temsili) onları manipüle etmeyi gerektirir.

Yine, TensorFlow'da modeller oluştururken, bu model keşfinin çoğu sizin için yapılır.

### Temel İşlemler
Temel matematiksel işlemlerin birçoğunu, `+, -, *` gibi Pyhton operatörlerini kullanarak doğrudan tensörler üzerinde gerçekleştirebilirsiniz.

In [31]:
# Toplama operatörünü kullanarak bir tensöre değerler ekleyebilirsiniz
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

`tf.constant()` kullandığımız için orijinal tensör değişmez (ekleme bir kopya üzerinde yapılır).

In [32]:
# Orjinal tensor değişmemiş
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [33]:
# çarpma işlemi
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [34]:
# Çıkarma
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

Eşdeğer TensorFlow işlevini de kullanabilirsiniz. TensorFlow işlevinin (mümkünse) kullanılması, bir [TensorFlow graph](https://www.tensorflow.org/tensorboard/graphs) parçası olarak çalıştırıldığında daha sonra satırda hızlandırılma avantajına sahiptir.

In [35]:
# '*' (çarpma) operatörünün tensorflow işlevi eşdeğerini kullanın
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [36]:
# orjinal tensor yine değişmez, işlem kopya üzerinden yapılır
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

### Matrix Çarpımı

Makine öğrenmesi algoritmalarında en yaygın işlemlerden biri matris çarpımıdır.

TensorFlow, bu matris çarpma işlevini [`tf.matmul()`](https://www.tensorflow.org/api_docs/python/tf/linalg/matmul) yönteminde uygular.

Matris çarpımının hatırlanması gereken iki ana kuralı şunlardır:

1. İç boyutlar aynı olmalıdır:
  - `(3, 5) @ (3, 5)` çalışmaz
  - `(5, 3) @ (3, 5)` çalışmaz
  - `(3, 5) @ (5, 3)` çalışır
2. Ortaya çıkan matris, dış boyutların şekline sahiptir.
  - `(5, 3) @ (3, 5)` -> `(5, 5)`
  - `(3, 5) @ (5, 3)` -> `(3, 3)`


> Not: Python'da `'@'` matris çarpımının sembolüdür.

In [37]:
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [38]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

Bu örneklerin ikisi de işe yarar çünkü tensör değişkenimiz (2, 2) şeklindedir.

Ya uyumsuz şekillere sahip bazı tensörler yaratsaydık?

In [39]:
# (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [40]:
X @ Y

InvalidArgumentError: ignored

İki tensörü şekil (3, 2) hatalarıyla çarpmaya çalışmak, iç boyutlar eşleşmediğinden.

Şunlardan birine ihtiyacımız var:

- X'i `(2, 3)` olarak yeniden şekillendirin, böylece `(2, 3) @ (3, 2)` olur.
- Y'yi `(3, 2)` olarak yeniden şekillendirin, böylece `(3, 2) @ (2, 3)` olur.


Bunu ikisinden biriyle yapabiliriz:

- `tf.reshape()` - bir tensörü tanımlanmış bir şekle yeniden şekillendirmemize izin verir.
- `tf.transpose()` - belirli bir tensörün boyutlarını değiştirir.

<img src="https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-lining-up-dot-products.png" />

In [41]:
# 3,2 -> 2,3 boyutuna dönüştürme
print(Y.shape)
tf.reshape(Y, shape=(2,3))

(3, 2)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [42]:
# boyutları eşlediğimiz için şimdi çarpma işlemi gerçekleşecektir
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

Aynısını yeniden şekillendirilmiş bir X ile deneyelim, ancak bu sefer `tf.transpose()` ve `tf.matmul()` kullanacağız.

In [43]:
# transpose (3, 2) -> (2, 3)
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [44]:
# boyutları eşlediğimiz için şimdi çarpma işlemi gerçekleşecektir
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [45]:
# matmul'un parametrelerini kullanarakta aynı sonucu elde edebilirdik
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

X'i transpoze ederken veya Y'yi yeniden şekillendirirken ortaya çıkan şekillerdeki farka dikkat edin.

Bunun nedeni yukarıda belirtilen 2. kuraldır:
- `(3, 2) @ (2, 3)` -> `(2, 2)` `tf.matmul(tf.transpose(X), Y)` ile yapılır
- `(2, 3) @ (3, 2)` -> `(3, 3)` X @ `tf.reshape(Y, shape=(2, 3))` ile yapılır.

Bu tür bir veri manipülasyonu bir hatırlatmadır: zamanınızın çoğunu makine öğreniminde ve sinir ağlarıyla çalışarak verileri (tensörler biçiminde) çeşitli işlemlerle kullanılmak üzere (besleme gibi) kullanıma hazırlamak için harcarsınız.

### Nokta (The Dot) Çarpımı

Matrislerin birbiriyle çarpılması, nokta çarpımı olarak da adlandırılır.

`tf.matmul()` işlemini `tf.tensordot()` kullanarak gerçekleştirebilirsiniz.

In [46]:
# Nokta çarpımı X ve Y üzerinde gerçekleştirin (X'in aktarılması gerekir)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

Hem yeniden şekillendirme hem de devrilme çalışmasını kullanmanıza rağmen, her birini kullanırken farklı sonuçlar aldığınızı fark edebilirsiniz.

Önce `tf.transpose()` ile sonra `tf.reshape()` ile bir örnek görelim.

In [47]:
# X ve Y (transpoze edilmiş) arasında matris çarpımı gerçekleştirin
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [48]:
# X ve Y (yeniden şekillendirilmiş) arasında matris çarpımı gerçekleştirin
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [49]:
print("X: ", X.shape)
print("Y: ", Y.shape)

X:  (3, 2)
Y:  (3, 2)


In [50]:
tf.matmul(X, tf.transpose(Y))
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

Hmm... farklı değerlerle sonuçlanırlar.

Bu garip çünkü Y (a (3x2) matrisi ile uğraşırken), (2, 3)'e yeniden şekillendirmek ve onu transpoze etmek aynı şekle neden olur.

In [51]:
Y.shape, tf.reshape(Y, (2, 3)).shape, tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

Ancak Y üzerinde tf.reshape() ve tf.transpose() öğelerinin çağrılması mutlaka aynı değerlerle sonuçlanmaz.

In [52]:
print("Normal Y:")
print(Y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Görüldüğü gibi tf.reshape() ve tf.transpose() çıktıları Y üzerinde çağrıldığında aynı şekle sahip olmalarına rağmen farklıdır.

- `tf.reshape()` <br> - verilen tensörün şeklini değiştirin (önce) ve ardından değerleri göründükleri sırayla ekleyin (bizim durumumuzda 7, 8, 9, 10, 11, 12).
- `tf.transpose()` <br> - eksenlerin sırasını değiştirir, varsayılan olarak son eksen ilk olur, ancak sıra izin parametresi kullanılarak değiştirilebilir.

**Peki hangisini kullanmalısınız?**

Yine çoğu zaman bu işlemler (eğitim sırasında bir sinir ağı gibi çalıştırılması gerektiğinde sizin için uygulanacaktır).

Ancak genel olarak, bir matris çarpımı gerçekleştirdiğinizde ve iki matrisin şekilleri aynı hizada değilse, onları hizalamak için birini transpose (not reshape) yapacaksınız.

### Matris Çarpımı Çerezleri (tidbits)

- Y'nin yerini değiştirseydik, Y^T olarak temsil edilirdi (devrilme için büyük T harfine dikkat edin).
- Matris çarpımının uygulamalı bir demosunu deneyin: http://matrixmultiplication.xyz/ (aşağıda gösterilmiştir).

<img src="https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-matrix-multiply-crop.gif" />

### Bir tensörün veri tipini değiştirme

Bazen tensörünüzün varsayılan veri türünü değiştirmek isteyeceksiniz.

Bu, daha az kesinlik kullanarak hesaplama yapmak istediğinizde yaygındır (örneğin, 16 bit float'a karşı 32 bit float).

Daha az hassasiyetle hesaplama, mobil cihazlar gibi daha az bilgi işlem kapasitesine sahip cihazlarda kullanışlıdır (çünkü daha az bit, hesaplamalar için daha az alan gerektirir).

`tf.cast()` kullanarak bir tensörün veri tipini değiştirebilirsiniz.

In [53]:
# float32
B = tf.constant([1.7, 7.4])

# int32
C = tf.constant([1, 7])
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [54]:
#  int32 -> float32
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

### Mutlak Değer

Bazen tensörlerinizdeki öğelerin mutlak değerlerini (tüm değerler pozitif) istersiniz.

Bunu yapmak için `tf.abs()` kullanabilirsiniz.

In [55]:
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [56]:
# mutlak değer uygulama
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

### Min, Max, Mean, Sum (aggregation)

Tüm öğelerin minimum değeri, maksimum değeri, ortalaması ve toplamı gibi şeyleri bulmak için tensörleri hızlı bir şekilde toplayabilirsiniz (bütün bir tensör üzerinde bir hesaplama gerçekleştirin).

Bunu yapmak için, toplama yöntemleri tipik olarak, şu sözdizimine sahiptir: `Reduce()_[action]`, örneğin:
- **tf.reduce_min()**<br> - bir tensördeki minimum değeri bulun.
- **tf.reduce_max()**<br> - bir tensördeki maksimum değeri bulun (en yüksek tahmin olasılığını bulmak istediğinizde faydalıdır).
- **tf.reduce_mean()**<br> - bir tensördeki tüm öğelerin ortalamasını bulun.
- **tf.reduce_sum()**<br> - bir tensördeki tüm öğelerin toplamını bulun.
- **Not:**<br> tipik olarak bunların her biri matematik modülünün altındadır, ör. tf.math.reduce_min() ancak tf.reduce_min() takma adını kullanabilirsiniz.

In [57]:
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([70, 85, 65, 74, 38, 75, 34, 64, 87, 13,  0,  2, 81, 90,  8,  6,  3,
       43, 97,  1, 39, 30, 89, 95, 40, 52, 89, 70, 67, 75, 68, 69, 99,  7,
       13,  3, 51, 60, 33, 78, 68, 32, 76,  3, 84, 78, 44, 66, 77, 48])>

In [58]:
# min 
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [59]:
# max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [60]:
# mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [61]:
# sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2639>

Benzer yöntemleri kullanarak bir tensördeki öğelerin standart sapmasını `(tf.reduce_std())` ve varyansını `(tf.reduce_variance())` de bulabilirsiniz.

### Konumsal Maksimum ve Minimumu Bulma

Maksimum değerin oluştuğu bir tensörün konumunu bulmaya ne dersiniz?

Bu, etiketlerinizi (['Yeşil', 'Mavi', 'Kırmızı'] deyin) tahmin olasılık tensörünüzle (ör. [0.98, 0.01, 0.01]) hizalamak istediğinizde yararlıdır.

Bu durumda, tahmin edilen etiket (en yüksek tahmin olasılığına sahip olan) 'Yeşil' olacaktır.

Aynısını minimum (gerekirse) için aşağıdakilerle yapabilirsiniz:

- **tf.argmax()**<br> - verilen bir tensördeki maksimum elemanın konumunu bulun.
- **tf.argmin()**<br> - verilen bir tensördeki minimum elemanın konumunu bulun.

In [62]:
# 0 ile 1 arasında 50 değere sahip bir tensör oluşturun
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.53697548, 0.77006251, 0.27002538, 0.1722545 , 0.1213745 ,
       0.88281511, 0.54574378, 0.31182952, 0.32899584, 0.68739552,
       0.14740686, 0.75410067, 0.39132619, 0.39968775, 0.36370828,
       0.04887278, 0.12538255, 0.29049129, 0.83654382, 0.63480792,
       0.01365383, 0.77700814, 0.0147493 , 0.29836945, 0.62383077,
       0.80137411, 0.55520553, 0.14574827, 0.40175651, 0.10670131,
       0.34050512, 0.21557382, 0.01250354, 0.51278339, 0.7956046 ,
       0.18686978, 0.38909812, 0.21060396, 0.16508862, 0.1481137 ,
       0.28258929, 0.11458198, 0.8273633 , 0.18710048, 0.33499017,
       0.37171141, 0.58226503, 0.14694826, 0.95996193, 0.92466082])>

In [63]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [64]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=32>

In [65]:
# Find the maximum element position of F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}") 
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}") 
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 48
The maximum value of F is: 0.9599619320535077
Using tf.argmax() to index F, the maximum value of F is: 0.9599619320535077
Are the two max values the same (they should be)? True


### Squeezing a Tensor

Bir tensörden tek boyutları çıkarmanız gerekiyorsa (1 boyutundaki boyutlar), tf.squeeze() öğesini kullanabilirsiniz.

- `tf.squeeze()` - bir tensörden 1'in tüm boyutlarını kaldırır.

In [66]:
# rank'ı 5 olan 0-100 arası 50 sayılı tensor
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [67]:
# Sıkıştırma tensörü G (1 boyutun tümünü kaldırın)
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

### One-hot Encoding

Eğer bir indeks tensörünüz varsa ve onu tek-sıcak kodlamak istiyorsanız, tf.one_hot() kullanabilirsiniz.

Ayrıca derinlik parametresini de (tek tuşla kodlamak istediğiniz seviye) belirtmelisiniz.

In [68]:
# Bir dizin listesi oluşturun
some_list = [0, 1, 2, 3]

# Bir sıcak onları kodlamak
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

Varsayılan 0 ve 1 yerine on_value ve off_value için değerler de belirtebilirsiniz.

In [69]:
# Açık ve kapalı kodlama için özel değerler belirtin
tf.one_hot(some_list, depth=4, on_value="We're live!", off_value="Offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"We're live!", b'Offline', b'Offline', b'Offline'],
       [b'Offline', b"We're live!", b'Offline', b'Offline'],
       [b'Offline', b'Offline', b"We're live!", b'Offline'],
       [b'Offline', b'Offline', b'Offline', b"We're live!"]], dtype=object)>

### Kare Alma, Log, Karekök

Bir aşamada gerçekleştirmek istediğiniz diğer birçok yaygın matematiksel işlem muhtemelen mevcuttur.

Bir göz atalım:

- **tf.square()**<br> - bir tensördeki her değerin karesini alın.
- **tf.sqrt()**<br> - bir tensördeki her değerin karekökünü alın (not: öğelerin yüzer olması gerekir, aksi takdirde bu hata verir).
- **tf.math.log()**<br> - bir tensördeki her değerin doğal günlüğünü alın (elemanların yüzmesi gerekir).

In [70]:
# yeni bir tensor oluşturma
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [71]:
# kare
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [72]:
# Karekökü bulun, tamsayı olmaması gerekir
tf.sqrt(H)

InvalidArgumentError: ignored

In [73]:
# H'yi float32 olarak değiştirin
H = tf.cast(H, dtype=tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [74]:
# karekökü bul
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [75]:
# log bulun (girişin ayrıca kayan olması gerekir)
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### tf.Variable Tensörleri Manipüle Etme
`tf.Variable()` ile oluşturulan tensörler, aşağıdaki gibi yöntemler kullanılarak yerinde değiştirilebilir:

- **.assign()** - bir değişken tensörün belirli bir dizinine farklı bir değer atayın.
- **.add_assign()** - mevcut bir değere ekleyin ve onu bir değişken tensörünün belirli bir dizininde yeniden atayın.

In [79]:
# Değişken bir tensör oluşturun
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [80]:
# bir 50 değeri atayın
I.assign([0, 1, 2, 3, 50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [81]:
# Değişiklik yerinde gerçekleşir (son değer şimdi 4 değil 50'dir)
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [82]:
# I'deki her öğeye 10 ekleyin
I.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

In [83]:
# Yine, değişiklik yerinde olur
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

## Tensor ve NumPy

Tensör oluşturmak için NumPy dizilerini kullanmak gibi, NumPy dizileriyle etkileşime giren bazı tensör örnekleri gördük.

Tensörler ayrıca aşağıdakiler kullanılarak NumPy dizilerine dönüştürülebilir:
- **np.array()**<br> - bir ndarray'e (NumPy'nin ana veri türü) dönüştürmek için bir tensör iletir.
- **tensor.numpy()**<br> - bir ndarray'e dönüştürmek için bir tensör çağırın.

Bunu yapmak, tensörleri yinelenebilir hale getirdiği ve NumPy'nin herhangi bir yöntemini onlarda kullanmamıza izin verdiği için yararlıdır.

In [84]:
# NumPy dizisinden bir tensör oluşturun
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [85]:
# np.array() ile tensör J'yi NumPy'ye dönüştürün
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [86]:
# .numpy() ile tensör J'yi NumPy'ye dönüştürün
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

Varsayılan olarak tensörler dtype=float32'ye sahiptir, burada NumPy dizileri dtype=float64'e sahiptir.

Bunun nedeni, sinir ağlarının (genellikle TensorFlow ile oluşturulur) genellikle daha az hassasiyetle (64 bit yerine 32 bit) çok iyi çalışabilmesidir.

In [88]:
# NumPy'den ve bir diziden bir tensör oluşturun
numpy_J = tf.constant(np.array([3., 7., 10.])) # float64 olacak (NumPy nedeniyle)
tensor_J = tf.constant([3., 7., 10.]) # float32 olacaktır (TensorFlow varsayılanı olduğu için)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## `@tf.function` kullanma

TensorFlow maceralarınızda, dekoratör `@tf.function` olan Python işlevleriyle karşılaşabilirsiniz.

Ama kısacası, dekoratörler bir işlevi şu ya da bu şekilde değiştirirler.

`@tf.function` dekoratör durumunda, bir Python işlevini çağrılabilir bir TensorFlow grafiğine dönüştürür. Bu, kendi Python işlevinizi yazdıysanız ve onu `@tf.function` ile süslerseniz, kodunuzu dışa aktardığınızda (potansiyel olarak başka bir cihazda çalışacak şekilde), TensorFlow onu bir kendisinin hızlı versiyonu (bir hesaplama grafiğinin parçası haline getirerek).

In [91]:
# basit bir function oluşturma
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [92]:
# Aynı işlevi oluşturun ve tf.function ile süsleyin
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

Yukarıdaki iki işlev (süslü olan ve olmayan) arasında hiçbir fark görmediyseniz, haklısınız.

Farkın çoğu perde arkasında oluyor. Ana olanlardan biri, mümkün olduğunda potansiyel kod hızlandırmalarıdır.

## GPU Erişim

`tf.config.list_physical_devices()` kullanarak bir GPU'ya erişiminiz olup olmadığını kontrol edebilirsiniz.

In [93]:
print(tf.config.list_physical_devices('GPU'))

[]


Yukarıdakiler boş bir dizi (veya hiçbir şey) verirse, bir GPU'ya erişiminiz olmadığı anlamına gelir (veya en azından TensorFlow onu bulamaz).

Google Colab'da çalışıyorsanız, Çalışma Zamanı -> Çalışma Zamanı Türünü Değiştir -> GPU Seç'e giderek bir GPU'ya erişebilirsiniz (not: bunu yaptıktan sonra not defteriniz yeniden başlar ve kaydettiğiniz tüm değişkenler kaybolur).

Çalışma zamanı türünüzü değiştirdikten sonra aşağıdaki hücreyi çalıştırın.

In [94]:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[]


Bir GPU'ya erişiminiz varsa, yukarıdaki hücre aşağıdaki gibi bir çıktı vermelidir:

`[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]`

Ayrıca !nvidia-smi kullanarak GPU'nuz hakkında bilgi bulabilirsiniz.

In [95]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



## ÖRNEK SORULAR

**tf.constant() kullanarak seçtiğiniz değerlerle bir vektör, skaler, matris ve tensör oluşturun.**

In [110]:
scalar = tf.constant(1)
vector = tf.constant([1,2])
matrix = tf.constant([[1,2],[3,4]])
tensor = tf.constant([[[1,2],[3,4]], [[5,6],[7,8]]])

**1'de oluşturduğunuz tensörlerin şeklini, sırasını ve boyutunu bulun.**

In [116]:
print("Tensor Shape: ", tensor.shape)
print("Tensor Dimension: ", tensor.ndim)
print("Tensor Type: ", matrix.dtype)

Tensor Shape:  (2, 2, 2)
Tensor Dimension:  3
Tensor Type:  <dtype: 'int32'>


**Shape değeri [5, 300] olan, 0 ile 1 arasında rastgele değerler içeren iki tensör oluşturun.**

In [127]:
tensor_1 = tf.constant([np.random.random(300), 
                        np.random.random(300),
                        np.random.random(300),
                        np.random.random(300),
                        np.random.random(300)])

tensor_2 = tf.constant([np.random.random(300), 
                        np.random.random(300),
                        np.random.random(300),
                        np.random.random(300),
                        np.random.random(300)])

print("tensor_1 shape: ", tensor_1.shape)
print("tensor_2 shape: ", tensor_2.shape)

tensor_1 shape:  (5, 300)
tensor_2 shape:  (5, 300)


**3'te oluşturduğunuz iki tensörü matris çarpımını kullanarak çarpın.**

In [129]:
tf.matmul(tensor_1, tf.transpose(tensor_2))

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[73.08692774, 65.85057701, 69.56896718, 70.51022121, 74.84731465],
       [72.97673219, 65.97858607, 68.19102992, 71.02093111, 72.545044  ],
       [80.8208249 , 67.72674431, 75.07914622, 74.45468399, 76.68195078],
       [77.98810584, 68.86230563, 73.62907957, 72.91510956, 76.24762241],
       [80.30045771, 68.85140491, 77.10544844, 74.85048498, 79.7906545 ]])>

**Nokta çarpımını kullanarak 3'te oluşturduğunuz iki tensörü çarpın.**

In [132]:
tf.tensordot(tensor_1, tf.transpose(tensor_2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[73.08692774, 65.85057701, 69.56896718, 70.51022121, 74.84731465],
       [72.97673219, 65.97858607, 68.19102992, 71.02093111, 72.545044  ],
       [80.8208249 , 67.72674431, 75.07914622, 74.45468399, 76.68195078],
       [77.98810584, 68.86230563, 73.62907957, 72.91510956, 76.24762241],
       [80.30045771, 68.85140491, 77.10544844, 74.85048498, 79.7906545 ]])>

**Şekil [224, 224, 3] ile 0 ile 1 arasında rastgele değerlere sahip bir tensör oluşturun.**

In [154]:
tensor_3 =  tf.constant(224*[224*[np.random.random(3)]])
tensor_3.shape

TensorShape([224, 224, 3])

**6'da oluşturduğunuz tensörün min ve max değerlerini bulun.**

In [174]:
min = tf.reduce_min(tensor_3)
max = tf.reduce_max(tensor_3)
print("min: ", min.numpy())
print("max: ", max.numpy())

min:  0.15631506275674423
max:  0.8021678826476675


**Rastgele şekil [1, 224, 224, 3] değerlerine sahip bir tensör oluşturuldu, ardından şekli [224, 224, 3] olarak değiştirmek için sıkıştırın.**

In [168]:
tensor_4 =  tf.constant([224*[224*[np.random.random(3)]]])
reshaped_tensor_4 = tf.reshape(tensor_4, shape=(224, 224, 3))
reshaped_tensor_4.shape

TensorShape([224, 224, 3])

**Kendi değer seçiminizi kullanarak [10] şeklinde bir tensör oluşturun, ardından maksimum değere sahip olan dizini bulun.**

In [178]:
my_array = [1,2,3,4,5,6,10,7,8,9]
tensor_5 = tf.constant(my_array)
print("max value index: ", tf.argmax(tensor_5).numpy())
print("max value: ", tf.reduce_max(tensor_5).numpy())

max value index:  6
max value:  10


**One-hot, 9'da oluşturduğunuz tensörü kodlayın.**

In [180]:
tf.one_hot(my_array, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>